@tenantName = havard
@baseAddress = https://localhost:7200/api/{{tenantName}}/Store
@storeId = 63ca7117-c4f5-4b0f-9ac2-4732dcb9639e
@branchId = 1

###
GET  {{baseAddress}}

### Get a SIngle Store
GET {{baseAddress}}/{{storeId}}/branch/{{branchId}}

### Create a Store
POST {{baseAddress}}
Content-Type: application/json

{
    "name": "DRAkE LEaD",
    "description": "Drake con festival",
    "code": "DR-Rake",
    "address": "Lagoon Express",
    "branchId": 1
}

### Get list of Stores
GET {{baseAddress}}/all/branch/{{branchId}}

### Updates a Store
PUT {{baseAddress}}/{{storeId}}/branch/{{branchId}}
Content-Type: application/json

{
    "name": "Drake Lead",
    "description": "Toby is awesome",
    "code": "DR-Rake",
    "address": "Lagoon Express",
}

### Deletes a Store
DELETE {{baseAddress}}/{{storeId}}/branch/{{branchId}}
