@tenantName = havard
@baseAddress = https://localhost:7211/api/{{tenantName}}/Supplier
@supplierId = 0c3709e9-c191-42d7-a7c1-f2cb11deefd1
@branchId = 1

### Get the default endpoint response
GET  {{baseAddress}}

### Get a Single SUpplier
GET {{baseAddress}}/{{supplierId}}/branch/{{branchId}}

### Add a Supplier
POST {{baseAddress}}
Content-Type: application/json

{
    "name": "Drake Supplies Services",
    "email": "Drake.Vine@gmail.com",
    "address": "Drake-Lake view avenue",
    "Phonenumber": "234707778936",
    "branchId": 1
}

### Get list of Suppliers
GET {{baseAddress}}/all/branch/{{branchId}}

### Updates a Store
PUT {{baseAddress}}/{{supplierId}}/branch/{{branchId}}
Content-Type: application/json

{
    "name": "Drake Lead",
    "email": "Drake.Vine@gmail.com",
    "phonenumbers": "234707778936",
    "address": "DR-Rake Lead Avenue."
}

### Deletes a Store
DELETE {{baseAddress}}/{{supplierId}}/branch/{{branchId}}